### ISSUE TITLE
Duration option string notation

### ISSUE THREAD

**Issue by Danman7** [mcfedr/mootools-fx-css3#8]
FX.CSS3 is awesome! And it works well on all browsers which made me implement it in my project.

I noticed a trivial issue where if the Tween duration option uses a string rather than an integer, for example 'short' or 'long', the transition will not fire. I believe that when the transitionDuration is set, there should be a check if this.options.duration returns a string, whether it meets Mootools criteria (is either short, medium or long) and if it so to be converted to an integer.

I should be able to find some time to fix it and make a pull request.

**Comment by SunboX** [comment]
Thanks a lot! A Pull request would be great, otherwise I will look into this issue if I get some time. :)

**Comment by Danman7** [comment]
Fixed by pull request #10
