### ISSUE TITLE
Transition timing function fallback

### ISSUE THREAD

**Issue by Danman7** [mcfedr/mootools-fx-css3#9]
Another minute issue I've come across is if the FX.Tween.CSS3 transition option returns something that does not match a property of transitionTimings, the transition doesn't occur. There should be a default timing function (e.g. linear) in these cases.

**Comment by SunboX** [comment]
Thanks a lot! This is a older project of mine. I'm not using mootools anymore (sadly). Didn't thought that FX.Tween.CSS3 would be useful to anyone anymore.

I will look into this issue if I get some time. :)

**Comment by Danman7** [comment]
Fixed by this bit of code:

if(!options.transition || !transitionTimings[options.transition]) {
    options.transition = 'sine:in:out';
}

Not, sure whether it was there before, but it is working now.
